### ISSUE TITLE
URL doesn't work

### ISSUE THREAD

**Issue by abidkhan124** [adibas03/crypto-will#19]
Hey the URL https://adibas03.github.io/crypto-will/ doesn't work. How do I run the app in local?

**Comment by abidkhan124** [comment]
Network might not be supported
🦊
We can't find any Ethereum accounts! Please check and make sure Metamask or your browser are pointed at the correct network and your account is unlocked.

**Comment by adibas03** [comment]
> Network might not be supported
> 🦊
> We can't find any Ethereum accounts! Please check and make sure Metamask or your browser are pointed at the correct network and your account is unlocked.

The contracts are only deployed on the testnets for now.
To access it, you need to switch to either the ropsten, kovan or Rinkeby networks to access the tool.

**Comment by adibas03** [comment]
@abidkhan124 I will be closing this now, as there is no update, Do not hesitate to leave a message, if you have more questions
