### ISSUE TITLE
Transaction unsuccessful while sending ether to beneficiary 

### ISSUE THREAD

**Issue by abidkhan124** [adibas03/crypto-will#21]
https://ropsten.etherscan.io/tx/0x87cfe87019d52b6316d225530b5e4bbd8b46ef9b88cbe1dafdbd82683bb2b98c

Please help to resolve the error.

**Comment by abidkhan124** [comment]
Also, can you please explain how 'willwallet' and 'wallet' are interacting with 'will'.

**Comment by adibas03** [comment]
> https://ropsten.etherscan.io/tx/0x87cfe87019d52b6316d225530b5e4bbd8b46ef9b88cbe1dafdbd82683bb2b98c
>
> Please help to resolve the error.

@abidkhan124 You need to first extend the `disposition` time, to be able to update the beneficiaries, using `postpone` call.

> Also, can you please explain how 'willwallet' and 'wallet' are interacting with 'will'.

The main component to achieve the Will functionality is the `Will` contract, the `Wallet` contract allows usage of the Will contract as a wallet, so, funds could be sent and transactions could be signed. The `WillWallet` implements both functionalities in one contract.

**Comment by abidkhan124** [comment]
Thanks man, appreciate it!
